#!/bin/bash
#this is cron start script
for i in {15..25};
do
echo "${i} 2 * * * root php /data/http/do.php ">>1.log;
echo "${i} 15 * * * root php /data/http/do.php">>1.log;
done;
echo ================start cron================
echo ==================done====================

